name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test_pull_request:
    name: Test pull request
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      EMAIL_LOGIN: 
      EMAIL_PASS: 
      RECIPIENT_EMAIL: 
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --no-optional
      - name: Run eslint
        run: npm run lint:ci
      - name: Build project
        run: npm run build
      - name: Run Jest tests
        run: npm run jest
      - name: Run migrations
        run: node_modules/.bin/sequelize db:migrate
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
